const airConditioned = {
  loadType:0,
  power: 1900,
  distance: 10,
  powerFactor: 0.9,
  voltageDrop: 2,
  aisolation: 0,
  temperature:25,
  loadPhases:1,
  perPhase:1,
  feeder_include_neutral_wire:false,
  pipe_material: 0,
  system_voltage:120
}

const spaceHeater = {
  loadType:1,
  power: 1320,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  aisolation: 0,
  temperature:25,
  loadPhases:1,
  perPhase:1,
  feeder_include_neutral_wire:true,
  pipe_material: 0,
  system_voltage:120
}

const dishWasher = {
  power: 1500,
  loadPhases:1,
  loadType:2,
  perPhase:1,
  distance: 10,
  powerFactor: 0.95,
  voltageDrop: 2,
  system_voltage:120,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire:true,
  pipe_material: 0,
}
const waterHeaterTankless = {
  power: 8000,
  loadPhases:2,
  loadType:3,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire:false,
  pipe_material: 0,
}
const oven = {
  power: 4500,
  loadPhases:2,
  loadType:4,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: true,
  pipe_material: 0,
}

const electricPan = {
  power: 1300,
  loadPhases:1,
  loadType:5,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:120,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: true,
  pipe_material: 0,
}
const clothesDryer1 = {
  power: 5000,
  loadPhases:2,
  loadType:6,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: false,
  pipe_material: 0,
}
const clothesDryer2 = {
  power: 2790,
  loadPhases:2,
  loadType:7,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: false,
  pipe_material: 0,
}
const crushingMachine = {
  power: 1500,
  loadPhases:1,
  loadType:8,
  perPhase:1,
  distance: 10,
  powerFactor: 0.9,
  voltageDrop: 2,
  system_voltage:120,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: true,
  pipe_material: 0,
}
const electricPump = {
  power: 1564,
  loadPhases:1,
  loadType:9,
  perPhase:1,
  distance: 10,
  powerFactor: 0.85,
  voltageDrop: 2,
  system_voltage:120,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: true,
  pipe_material: 0,
}
const toaster = {
  power: 1051,
  loadPhases:1,
  loadType:10,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: true,
  pipe_material: 0,
} 
const microWaveOven = {
  power: 1400,
  loadPhases:1,
  loadType:11,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: true,
  pipe_material: 0,
}
const moto3hp = {
  power: 3242,
  loadPhases:3,
  loadType:12,
  perPhase:1,
  distance: 10,
  powerFactor: 0.85,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: false,
  pipe_material: 0,
}
const kitchen = {
  power: 6000,
  loadPhases:2,
  loadType:13,
  perPhase:1,
  distance: 10,
  powerFactor: 1,
  voltageDrop: 2,
  system_voltage:208,
  aisolation: 0,
  temperature:25,
  feeder_include_neutral_wire: true,
  pipe_material: 0,
}


const cargasPredeterminadas = [ airConditioned, spaceHeater, dishWasher, waterHeaterTankless, oven,electricPan,clothesDryer1,clothesDryer2,crushingMachine,electricPump,toaster,microWaveOven, moto3hp,kitchen]
export {cargasPredeterminadas}